name: Deploy Branch Workflow

on:
  push:
    # Trigger on any branch push.
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
      # instance_type:
      #   description: 'AWS instance type'
      #   required: true
      #   default: 't2.micro'

jobs:
  determine_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code.
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Extract the branch name.
      - name: Get Branch Name
        id: get_branch
        run: echo "branch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      # Step 3: Determine branch type (develop, main, or JIRA branch if digits only).
      - name: Determine Branch Type
        id: branch_type
        shell: bash
        run: |
          BRANCH=${{ steps.get_branch.outputs.branch }}
          echo "Detected branch: $BRANCH"
          if [[ "$BRANCH" =~ ^[A-Za-z0-9]+$ ]]; then
            echo "branch_type=jira" >> $GITHUB_OUTPUT
          fi
          
      # Optional: Output the branch type for logging.
      - name: Show Branch Type
        run: echo "Branch type is ${{ steps.branch_type.outputs.branch_type }}"

      # Step 4: Deploy based on branch type.
      - name: Deploy Based on Branch Type
        run: echo "hello"